---
 - name: Playbook to install Littlest JuypyterHub
   become: true
   hosts: 
    - vms
   tasks: 
    - name: Install dependencies
      apt:
        update_cache: true
        state: present
        pkg:
         - python3 
         - python3-dev
         - git
         - curl
         - unzip
    - name: "Get the install script"
      get_url:
        url: https://tljh.jupyter.org/bootstrap.py
        dest: /home/adminuser/bootstrap.py
      become: false
    - name: "Run bootstrap"
      ansible.builtin.shell: 
        python3 /home/adminuser/bootstrap.py \
        --admin fergus:tocodedisworkshop \
        --admin stephen:tocodedisworkshop \
        --admin matt:tocodedisworkshop \
        \
        --admin frazer:tocodedisworkshop \
        --admin spinoza:tocodedisworkshop \
        --admin mikael:tocodedisworkshop \
        --admin will:tocodedisworkshop \
        --admin nick-beno:tocodedisworkshop \
        --admin miles:tocodedisworkshop \
        --admin irene:tocodedisworkshop \
        --admin paul:tocodedisworkshop \
        --admin ameer-mahmood:tocodedisworkshop \
        --admin stanislav:tocodedisworkshop \
        --admin amanda:tocodedisworkshop \
        --admin kevin:tocodedisworkshop \
        --admin birju:tocodedisworkshop \
        --admin steven-brewer:tocodedisworkshop \
        --admin naksatra:tocodedisworkshop \
        --admin dorathy-yuan-jane:tocodedisworkshop \
        --admin james:tocodedisworkshop \
        --admin hugh:tocodedisworkshop \
        \
        --admin steven-ziolkowski:tocodedisworkshop \
        --admin nick-lamb:tocodedisworkshop \
        --admin emmalee:tocodedisworkshop \
        --admin mohammad:tocodedisworkshop \
        --admin richard:tocodedisworkshop \
        --admin robert:tocodedisworkshop \
        --admin andrew-ambrose-thurman:tocodedisworkshop \
        --admin ross:tocodedisworkshop \
        --admin max:tocodedisworkshop \
        --admin daniel-drummond:tocodedisworkshop \
        --admin lewis:tocodedisworkshop \
        --admin prajna:tocodedisworkshop \
        --admin mukilan:tocodedisworkshop \
        --admin jonathan:tocodedisworkshop \
        --admin olivia:tocodedisworkshop \
        --admin inken:tocodedisworkshop \
        --admin jack:tocodedisworkshop \
        --admin al:tocodedisworkshop \
        --admin shelley:tocodedisworkshop \
        --admin daniel-routledge:tocodedisworkshop \
        --admin veronika:tocodedisworkshop \
        --admin george:tocodedisworkshop \
        --admin ather:tocodedisworkshop \
        --admin mark:tocodedisworkshop \
        --admin andrew-besford:tocodedisworkshop \
        --admin chioma:tocodedisworkshop \
        --admin marie:tocodedisworkshop \
        --admin david:tocodedisworkshop \
        --admin monika:tocodedisworkshop \
        --admin ben:tocodedisworkshop \
        --admin ahood:tocodedisworkshop \
        --admin shruti:tocodedisworkshop

      args:
        creates: /etc/systemd/system/jupyterhub.service
    
    - name: "Enable HTTPS"
      ansible.builtin.shell:
        sudo tljh-config set https.enabled true &&
        sudo tljh-config set https.letsencrypt.email {{ email }} &&
        sudo tljh-config add-item https.letsencrypt.domains {{ hostname }} &&
        sudo tljh-config reload proxy

    - name: "Install packages"
      ansible.builtin.shell: /opt/tljh/user/bin/pip install pandas matplotlib

    - name: "Create directory for custom settings"
      ansible.builtin.shell: sudo mkdir -p /opt/tljh/user/share/jupyter/lab/settings

    - name: Upload custom settings
      ansible.builtin.copy:
        src: overrides.json
        dest: /opt/tljh/user/share/jupyter/lab/settings/overrides.json

    - name: Reload configuration
      ansible.builtin.shell: sudo tljh-config reload

    - name: Upload data
      ansible.builtin.unarchive:
        src: upload.zip
        dest: /etc/skel
        creates: /etc/skel/python.ipynb
